version: 1
template:
  id: cloudflare-sql1
  title: Cloudflare D1 SQL
priority:
  - type: stack-base
    modules:
      - stacks/cloudflare-sql1/base
  - type: stack-extension
    modules:
      - stacks/cloudflare-sql1/testing
  - type: cross-cutting
    modules:
      - cross-cutting/docs
      - cross-cutting/security
      - cross-cutting/performance
