version: 1
template:
  id: cloudflare-workers
  title: Cloudflare Workers
priority:
  - type: stack-base
    modules:
      - stacks/cloudflare-workers/base
  - type: stack-extension
    modules:
      - stacks/cloudflare-workers/testing
  - type: cross-cutting
    modules:
      - cross-cutting/docs
      - cross-cutting/security
      - cross-cutting/performance
