version: 1
template:
  id: hono
  title: Hono
priority:
  - type: stack-base
    modules:
      - stacks/hono/base
  - type: stack-extension
    modules:
      - stacks/hono/testing
  - type: cross-cutting
    modules:
      - cross-cutting/docs
      - cross-cutting/security
      - cross-cutting/performance
