version: 1
template:
  id: nodejs
  title: Node.js
priority:
  - type: stack-base
    modules:
      - stacks/nodejs/base
  - type: stack-extension
    modules:
      - stacks/nodejs/testing
  - type: cross-cutting
    modules:
      - cross-cutting/docs
      - cross-cutting/security
      - cross-cutting/performance
