version: 1
core: true
template:
  id: postgresql
  title: PostgreSQL stack
priority:
  - type: stack-base
    modules:
      - stacks/postgresql/base
  - type: stack-extension
    modules:
      - stacks/postgresql/testing
  - type: cross-cutting
    modules:
      - cross-cutting/security
      - cross-cutting/testing
      - cross-cutting/accessibility
      - cross-cutting/performance
      - cross-cutting/docs
      - cross-cutting/cursor-ide-basics
