version: 1
core: true
template:
  id: ruby-middleman
  title: Ruby Middleman site
priority:
  - type: stack-base
    modules:
      - stacks/ruby/base
      - stacks/ruby-middleman/base
  - type: stack-extension
    modules: []
  - type: cross-cutting
    modules:
      - cross-cutting/security
      - cross-cutting/testing
      - cross-cutting/performance
      - cross-cutting/docs
