version: 1
template:
  id: ruby
  title: Ruby
priority:
  - type: stack-base
    modules:
      - stacks/ruby/base
  - type: stack-extension
    modules:
      - stacks/ruby/testing
  - type: cross-cutting
    modules:
      - cross-cutting/docs
      - cross-cutting/security
      - cross-cutting/performance
