version: 1
template:
  id: ruby-middleman
  title: Ruby Middleman
priority:
  - type: stack-base
    modules:
      - stacks/ruby-middleman/base
  - type: stack-extension
    modules:
      - stacks/ruby-middleman/testing
  - type: cross-cutting
    modules:
      - cross-cutting/docs
      - cross-cutting/security
      - cross-cutting/performance
