version: 1
template:
  id: rust
  title: Rust
priority:
  - type: stack-base
    modules:
      - stacks/rust/base
  - type: stack-extension
    modules:
      - stacks/rust/testing
  - type: cross-cutting
    modules:
      - cross-cutting/docs
      - cross-cutting/security
      - cross-cutting/performance
