version: 1
template:
  id: tailwind
  title: Tailwind CSS
priority:
  - type: stack-base
    modules:
      - stacks/tailwind/base
  - type: stack-extension
    modules:
      - stacks/tailwind/testing
  - type: cross-cutting
    modules:
      - cross-cutting/docs
      - cross-cutting/security
      - cross-cutting/performance
