version: 1
template:
  id: vite
  title: Vite
priority:
  - type: stack-base
    modules:
      - stacks/vite/base
  - type: stack-extension
    modules:
      - stacks/vite/testing
  - type: cross-cutting
    modules:
      - cross-cutting/docs
      - cross-cutting/security
      - cross-cutting/performance
